version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  api-gateway:
    build: .
    command: node dist/apps/api-gateway/main
    ports:
      - '3004:3004'
    depends_on:
      - redis
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3004/health']
      interval: 10s
      timeout: 5s
      retries: 3
    env_file: .env

  user-service:
    build: .
    command: node dist/apps/user-service/main
    depends_on:
      - redis
    env_file: .env

  order-service:
    build: .
    command: node dist/apps/order-service/main
    depends_on:
      - redis
    env_file: .env