version: '3.8'

services:
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - '6379:6379'

  api-gateway:
    build: .
    command: node dist/apps/api-gateway/main
    ports:
      - '3004:3004'
    # depends_on:
    #   - redis
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3004/health']
      interval: 10s
      timeout: 5s
      retries: 3
    env_file: .env

  user-service:
    build: .
    command: node dist/apps/user-service/main
    # depends_on:
    #   - redis
    env_file: .env

  order-service:
    build: .
    command: node dist/apps/order-service/main
    # depends_on:
    #   - redis
    env_file: .env

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1